services:
  web:
    working_dir: /var/www/html
    build: .
    volumes:
      - /Users/ralph/Documents/golf-front-end:/var/www/html
    ports:
      - 80:80
  database:
    image: mariadb:latest
    volumes:
      - /Users/ralph/Documents/Docker Databases/Golf2:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=database
