services:
  web:
    working_dir: /var/www/html
    build: .
    volumes:
      - /Users/ralph/Documents/golf:/var/www/html
    ports:
      - 80:80
  database:
    image: mysql:8.2.0
    volumes:
      - /Users/ralph/Documents/Docker Databases/Golf:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=database
