name: Deploy

on: [push]

jobs:
  playwright:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Install Chromium browser
        run: npx playwright install chromium

      - name: Run Playwright tests
        run: npx start-server-and-test "npm run dev" http://localhost:5173 "npx playwright test"

  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Download PHPUnit
        run: |
          ls 
          pwd
          wget https://phar.phpunit.de/phpunit-10.phar
          chmod +x phpunit-10.phar 
          php phpunit-10.phar --version

      - name: Run tests
        run: |
          ls
          pwd
          php phpunit-10.phar tests_php

  vite:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run test --coverage

  deploy:
    runs-on: ubuntu-latest
    needs: [phpunit, vite, playwright]
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4

      - name: Run build
        run: npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER_NAME }}
          username: ${{ secrets.FTP_USER_NAME }}
          password: ${{ secrets.FTP_USER_PASSWORD }}
