name: PHPUnit

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download PHPUnit
        run: |
          ls 
          pwd
          wget https://phar.phpunit.de/phpunit-10.phar
          chmod +x phpunit-10.phar 
          phpunit --version

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Run tests
        run: php -v
